name: devfest
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.0.2
  - nltk=3.4
  - notebook=5.7.1
  - numpy=1.16.0
  - pandas=0.24.0
  - pillow=5.4.1
  - pymc3=3.6
  - python=3.6
  - requests=2.20
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - seaborn=0.9.0
